# Generated by Django 3.1.1 on 2020-09-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteAPI', '0002_auto_20200909_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
